export const NEWS_FETCH_REQUESTED = 'NEWS_FETCH_REQUESTED';
export const NEWS_FETCH_SUCCEEDED = 'NEWS_FETCH_SUCCEEDED';
export const NEWS_FETCH_FAILED = 'NEWS_FETCH_FAILED';

export const TOPNEWS_FETCH_REQUESTED = 'TOPNEWS_FETCH_REQUESTED';
export const TOPNEWS_FETCH_SUCCEEDED = 'TOPNEWS_FETCH_SUCCEEDED';
export const TOPNEWS_FETCH_FAILED = 'TOPNEWS_FETCH_FAILED';
